---
title: "R Notebook"
output: html_notebook
---


```{r}
library(icd)
library(tidyr)
library(dplyr)
```

```{r}
comorbid_map = icd9_map_ahrq
mx <- max(lengths(comorbid_map))
df <- data.frame(lapply(comorbid_map, `length<-`, mx))
ICD9_ahrq <- gather(df, ahrq, ICD9, CHF:Depression, na.rm = TRUE)

write.csv(ICD9_ahrq,"ICD9_ahrq.csv",row.names = FALSE)

# 33 duplicates
df <- ICD9_ahrq %>%
       group_by(ICD9) %>%
       filter(n()>1)
```

```{r}
comorbid_map = icd9_map_elix
mx <- max(lengths(comorbid_map))
df <- data.frame(lapply(comorbid_map, `length<-`, mx))
ICD9_elix <- gather(df, elix, ICD9, CHF:Depression, na.rm = TRUE)
write.csv(ICD9_elix,"ICD9_elix.csv",row.names = FALSE)

# 6 duplicates
df <- ICD9_elix %>%
       group_by(ICD9) %>%
       filter(n()>1)
```

```{r}
#comorbid_map = icd9_map_hcc
#mx <- max(lengths(comorbid_map))
#df <- data.frame(lapply(comorbid_map, `length<-`, mx))
#long <- gather(df, group, ICD9, XXXXX)
#ICD9_hcc <- long %>% drop_na()
```


```{r}
comorbid_map = icd9_map_quan_deyo
mx <- max(lengths(comorbid_map))
df <- data.frame(lapply(comorbid_map, `length<-`, mx))
ICD9_quan_deyo <- gather(df, quan_deyo, ICD9, MI:HIV, na.rm = TRUE)
write.csv(ICD9_quan_deyo,"ICD9_quan_deyo.csv",row.names = FALSE)

#28 duplicates
df <- ICD9_quan_deyo %>%
       group_by(ICD9) %>%
       filter(n()>1)
```

```{r}
comorbid_map = icd9_map_quan_elix
mx <- max(lengths(comorbid_map))
df <- data.frame(lapply(comorbid_map, `length<-`, mx))
ICD9_quan_elix <- gather(df, quan_elix, ICD9, CHF:Depression, na.rm = TRUE)
write.csv(ICD9_quan_elix,"ICD9_quan_elix.csv",row.names = FALSE)

#211 duplicates
df <- ICD9_quan_elix %>%
       group_by(ICD9) %>%
       filter(n()>1)
```


```{r}
ccs_labels <- read.table('ccs_labels_ICD9.csv', 
                   header=TRUE,
                   sep=',')
ccs_labels <- as.data.frame.matrix(ccs_labels)

comorbid_map = icd9_map_single_ccs
mx <- max(lengths(comorbid_map))
df <- data.frame(lapply(comorbid_map, `length<-`, mx))
ICD9_single_ccs <- gather(df, ccs_code, ICD9, X0:X2621, na.rm = TRUE)
ICD9_single_ccs$ccs_code<-gsub("X","", ICD9_single_ccs$ccs_code)
ICD9_single_ccs <- ICD9_single_ccs %>%
                  left_join(ccs_labels,by=c("ccs_code"="CCS.DIAGNOSIS.CATEGORIES")) %>%
                  rename(ccs_label = CCS.DIAGNOSIS.CATEGORIES.LABELS)
write.csv(ICD9_single_ccs,"ICD9_single_ccs.csv",row.names = FALSE)

#28 duplicates
df <- ICD9_single_ccs %>%
       group_by(ICD9) %>%
       filter(n()>1)
```

```{r}
# opted to not use this super table b/c it causes a lot of duplicate rows
# (i.e. 30k more than double total number of ICD9 codes)

super_comorbid <- ICD9_ahrq %>%
                  full_join(ICD9_elix, by="ICD9") %>%
                  full_join(ICD9_quan_deyo, by ="ICD9") %>%
                  full_join(ICD9_quan_elix, by="ICD9") #%>%
                  #full_join(ICD9_single_ccs, by="ICD9") %>%
                  #relocate(ICD9)

```

