data_path: "/hpc/group/kamaleswaranlab/EmoryDataset/EMR_RAW"
groupings_path: "/cwork/jfr29/Sepy/groupings"
output_path: "/cwork/jfr29/"
dictionary_paths:
  comorbidity_types:
    - "ICD9_ahrq"
    - "ICD9_elix"
    - "ICD9_quan_deyo"
    - "ICD9_quan_elix"
    - "ICD9_single_ccs"
    - "ICD10_ahrq"
    - "ICD10_elix"
    - "ICD10_quan_deyo"
    - "ICD10_quan_elix"
    - "ICD10_single_ccs"
  grounping_types:
    - "em_all_infusion_meds"
    - "em_grouping_labs"
    - "em_bed_labels"
  year_types:
    - "INFUSIONMEDS"
    - "LABS"
    - "VITALS"
    - "VENT"
    - "DEMOGRAPHICS"
    - "GCS"
    - "ENCOUNTER"
    - "CULTURES"
    - "BEDLOCATION"
    - "ORPROCEDURES"
    - "DIAGNOSIS"
yearly_instance:
  import_encounters:
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "ed_presentation_time"
      - "hospital_admission_date_time"
      - "hospital_discharge_date_time"
  import_demographics:
    drop_cols: []
    index_col: ["pat_id"]
    date_cols: [] # removed 'dob'
  import_infusion_meds:
    drop_cols: []
    numeric_cols:
      - "order_med_id"
      - "medication_id"
    anti_infective_group_name: "anti-infective"
    vasopressor_group_name: "vasopressor"
    index_col: ["csn"]
    date_cols:
      - "med_order_time"
      - "med_action_time"
      - "med_start"
      - "med_stop"
  import_labs:
    drop_cols: []
    group_cols:
      - "physionet"
      - "import"
      - "super_table_col_name"
      - "component_id"
    date_cols:
      - "collection_time"
      - "lab_result_time"
    index_col: ["csn"]
    numeric_cols: null
  import_vitals:
    drop_cols: []
    numeric_cols: "yearly_instance.vital_col_names"
    index_col: ["csn"]
    date_cols: ["recorded_time"]
    merge_cols: null
  import_vent:
    drop_cols: []
    index_col: ["csn"]
    numeric_cols:
      - "vent_rate_set"
      - "vent_tidal_rate_set"
      - "vent_tidal_rate_exhaled"
      - "peep"
      - "fio2"
    date_cols:
      - "recorded_time"
      - "vent_start_time"
      - "vent_stop_time"
  import_gcs:
    drop_cols: []
    index_col: ["csn"]
    numeric_col:
      - "gcs_eye_score"
      - "gcs_verbal_score"
      - "gcs_motor_score"
      - "gcs_total_score"
    date_cols: ["recorded_time"]
  import_cultures:
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "specimen_collect_time"
      - "order_time"
      - "lab_result_time"
  import_bed_locations:
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "bed_location_start"
      - "bed_location_end"
  import_procedures:
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "surgery_date"
      - "in_or_dttm"
      - "procedure_start_dttm"
      - "procedure_comp_dttm"
      - "out_or_dttm"
  import_diagnosis:
    drop_cols: []
    index_col: ["csn"]
    date_cols: ["dx_time_date"]