# SETUP INSTRUCTIONS
## assign unique-encounters_path to the path of the unique encounters file

# SLURM CONFIGURATION
num_processes: "7"
processor_assignment: "1"

# PIPELINE INSTRUCTIONS
make_yearly_pickle: "yes" # yes: make pickle files, no: do not make pickle files
make_supertables: "yes" # yes: make supertables, no: do not make supertables


# FILE PATHS
data_path: "/hpc/group/kamaleswaranlab/EmoryDataset/EMR_RAW/noPHI"
groupings_path: "groupings"
yearly_pickle_output_path: "/hpc/group/kamaleswaranlab/EmoryDataset/EMR_YEARLY_PICKLES/"
supertable_output_path: "/hpc/group/kamaleswaranlab/EmoryDataset/EMR_SuperTables_test/"
encounters_path: "ENCOUNTER_FILE"
dataset_identifier: "em_y"

# CSN FILTERING
encounter_type: "IN" # "EM" = Emergency, "IN" = Inpatient, "all" = all encounter types ????? 
age: "adult" # "adult": age >= 18, "pediatric": age < 18, "all": all ages
specific_enc_filter: "no" # "yes": only specific encounters, "no": all encounters
#specific_enc_filter_list: []


dictionary_paths:
  # DICTIONARY PATH KEYWORDS AND STRING FOR THE GLOB FUNCTION TO MATCH IN THE groupings/comorbidities FOLDER
  comorbidity_types:
    - ["ICD9_ahrq", "*ICD9_ahrq*"]
    - ["ICD9_elix", "*ICD9_elix*"]
    - ["ICD9_quan_deyo", "*ICD9_quan_deyo*"]
    - ["ICD9_quan_elix", "*ICD9_quan_elix*"]
    - ["ICD9_single_ccs", "*ICD9_single_ccs*"]
    - ["ICD10_ahrq", "*ICD10_ahrq*"]
    - ["ICD10_elix", "*ICD10_elix*"]
    - ["ICD10_quan_deyo", "*ICD10_quan_deyo*"]
    - ["ICD10_quan_elix", "*ICD10_quan_elix*"]
    - ["ICD10_single_ccs", "*ICD10_single_ccs*"]
  # DICTIONARY PATH KEYWORDS AND STRING FOR THE GLOB FUNCTION TO MATCH IN THE groupings/ FOLDER
  grouping_types:
    - ["infusion_meds", "em_all_infusion_meds.csv"]
    - ["grouping_labs", "em_grouping_labs.csv"]
    - ["bed_labels", "em_bed_labels.csv"]
    - ["grouping_fluids", "em_fluids_labels.csv"]
    - ["variable_chart", "em_variable_chart.csv"]
    - ["grouping_vent", "em_vent_labels.csv"]
  flatfile_types: 
    # DICTIONARY PATH KEYWORDS AND STRING FOR THE GLOB FUNCTION TO MATCH IN THE data_path/year/ FOLDER
    - ["INFUSIONMEDS", "*INFUSIONMEDS*"]
    - ["LABS", "*LABS*"]
    - ["VITALS", "*VITALS*"]
    - ["VENT", "*VENT_WITHO2*"]
    - ["DEMOGRAPHICS", "*DEMOGRAPHICS*"]
    - ["GCS", "*GCS*"]
    - ["ENCOUNTER", "*ENCOUNTER*"]
    - ["CULTURES", "*CULTURES*"]
    - ["BEDLOCATION", "*BEDLOCATION*"]
    - ["ORPROCEDURES", "*ORPROCEDURES*"]
    - ["DIAGNOSIS", "*DIAGNOSIS*"]
    - ["CPT_PROCEDURES", "*CPT*"]
    - ["ICD_PROCEDURES", "*ICDPROCEDURES*"]
    - ["CLINICAL_NOTES", "*CLINICAL_NOTES*"]
  combined_files:
    # DICTIONARY PATH KEYWORDS AND STRING FOR THE GLOB FUNCTION TO MATCH IN THE data_path/ FOLDER
    - ["DIALYSIS", "DIALYSIS_14_21.dsv"] 
    - ["IN_OUT", "CJSEPSIS_OUT_EO3.csv"]
    - ["RADIOLOGY_NOTES", "all_radiology_notes.csv"]

# YEARLY INSTANCE FUNCTIONS AND PARAMETERS
yearly_instance:
  import_demographics:
    file_key: "DEMOGRAPHICS"
    drop_cols: []
    index_col: ["pat_id"]
    date_cols: [] 
  import_encounters:
    file_key: "ENCOUNTER"
    drop_cols: 
      - "admit_reason"
      - "insurance_status"
      - "total_vent_days"
      - "total_hosp_days"
      - "discharge_status" # These fields were null in the data files. Insurance status was dropped because it wasn't needed for our analysis.
    index_col: ["csn"]
    date_cols:
      - "ed_presentation_time"
      - "hospital_admission_date_time"
      - "hospital_discharge_date_time"
  import_infusion_meds:
    file_key: "INFUSIONMEDS"
    drop_cols: []
    numeric_cols:
      - "order_med_id"
      - "medication_id"
    anti_infective_group_name: "anti-infective"
    vasopressor_group_name: "vasopressor"
    index_col: ["csn"]
    date_cols:
      - "med_order_time"
      - "med_action_time"
      - "med_start"
      - "med_stop"
  import_labs:
    file_key: "LABS"
    drop_cols: []
    date_cols:
      - "collection_time"
      - "lab_result_time"
  import_vitals:
    file_key: "VITALS"
    drop_cols: []
    index_col: ["csn"]
    date_cols: ["recorded_time"]
    merge_cols: []
  import_vent:
    file_key: "VENT"
    drop_cols: []
    index_col: ["csn"]
    numeric_cols:
      - "vent_rate_set"
      - "vent_tidal_rate_set"
      - "vent_tidal_rate_exhaled"
      - "peep"
      - "fio2"
    date_cols:
      - "recorded_time"
      - "vent_start_time"
      - "vent_stop_time"
  import_dialysis:
    file_key: "DIALYSIS"
    drop_cols: 
      - "empi"
      - "encounter_id"
    index_col: ["csn"]
    date_cols:
      - "service_timestamp"
  import_gcs:
    file_key: "GCS"
    drop_cols: []
    index_col: ["csn"]
    numeric_col:
      - "gcs_eye_score"
      - "gcs_verbal_score"
      - "gcs_motor_score"
      - "gcs_total_score"
    date_cols: ["recorded_time"]
  import_cultures:
    file_key: "CULTURES"
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "specimen_collect_time"
      - "order_time"
      - "lab_result_time"
  import_bed_locations:
    file_key: "BEDLOCATION"
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "bed_location_start"
      - "bed_location_end"
  import_procedures:
    file_key: "ORPROCEDURES"
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "surgery_date"
      - "in_or_dttm"
      - "procedure_start_dttm"
      - "procedure_comp_dttm"
      - "out_or_dttm"
  import_diagnosis:
    file_key: "DIAGNOSIS"
    drop_cols: []
    index_col: ["csn"]
    date_cols: ["dx_time_date"]
  import_cpt_procedures:
    file_key: "CPT_PROCEDURES"
    drop_cols: 
      - "group_modifier_cpt_desc"
      - "modifier_cpt_seq_num"
    index_col: ["csn"]
    date_cols:
      - "procedure_day"
      - "procedure_dttm"
  import_icd_procedures:
    file_key: "ICD_PROCEDURES"
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "procedure_date"
  import_in_out:
    file_key: "IN_OUT"
    drop_cols: []
    numeric_cols: [] 
    index_col: ["csn"]
    date_cols:
      - "service_date"
      - "service_ts"
      - "order_ts"
  import_radiology_notes:
    file_key: "RADIOLOGY_NOTES"
    drop_cols: []
    index_col: ["patient_id"]
    date_cols:
      - "day_verified"
    text_col: "doc_text"
    clean_text: true
    max_length: null
  import_clinical_notes:
    file_key: "CLINICAL_NOTES"
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "note_date"
      - "documented_date"
    text_col: "note_text"
    clean_text: true
    extract_sections: true
    max_length: null


# COMORBIDITY SUMMARY KEYWORDS
comorbidity_summary:
  - "ICD10_quan_deyo"
  - "ICD10_quan_elix"
  # - "ICD9_ahrq"
  # - "ICD9_elix"
  # - "ICD9_quan_deyo"
  # - "ICD9_quan_elix"
  # - "ICD9_single_ccs"
  # - "ICD10_ahrq"
  # - "ICD10_elix"
  # - "ICD10_single_ccs"


# SEPSIS SUMMARY DIRECTORY PATHS
sepsis_summary: "em_sepsis_summary"
sepsis_summary_types:
  - "sofa_summary"
  - "sep3_summary"
  - "sirs_summary"
  - "sep2_summary"
  - "encounter_summary"
  - "error_summary"
  # - "ahrq_ICD10_summary"
  # - "elix_ICD10_summary"
  - "quan_deyo_ICD10_summary"
  - "quan_elix_ICD10_summary"
  # - "ccs_ICD10_summary"