# SETUP INSTRUCTIONS
## assign unique-encounters_path to the path of the unique encounters file

# SLURM CONFIGURATION
num_processes: "7"
processor_assignment: "1"

# PIPELINE INSTRUCTIONS
make_yearly_pickle: "yes" # yes: make pickle files, no: do not make pickle files
make_supertables: "yes" # yes: make supertables, no: do not make supertables


# FILE PATHS
data_path: "/hpc/group/kamaleswaranlab/EmoryDataset/EMR_RAW"
groupings_path: "../groupings"
pickle_output_path: "/hpc/group/kamaleswaranlab/EmoryDataset/EMR_SuperTables/"
dictionary_output_path: "/hpc/group/kamaleswaranlab/EmoryDataset/EMR_YearlyDictionaries/"
bed_unit_csv_fname:  "../AdditionalInformation/bed_units_to_icu_AH.csv"
variable_bounds_csv_fname : "../AdditionalInformation/Variable_Chart.csv"
dialysis_info_csn_fname: "/hpc/group/kamaleswaranlab/EmoryDataset/EMR_RAW/PEACH_HD_CRRT.csv"
encounters_path: "ENCOUNTER_FILE"
dataset_identifier: "em_y"

# CSN FILTERING
encounter_type: 1 # "EM" = Emergency, "IN" = Inpatient, "all" = all encounter types ????? 
age: "adult" # "adult": age >= 18, "pediatric": age < 18, "all": all ages
specific_enc_filter: "no" # "yes": only specific encounters, "no": all encounters
#specific_enc_filter_list: 

# DICTIONARY PATH KEWORDS
dictionary_paths:
  comorbidity_types:
    - "ICD9_ahrq"
    - "ICD9_elix"
    - "ICD9_quan_deyo"
    - "ICD9_quan_elix"
    - "ICD9_single_ccs"
    - "ICD10_ahrq"
    - "ICD10_elix"
    - "ICD10_quan_deyo"
    - "ICD10_quan_elix"
    - "ICD10_single_ccs"
  grouping_types:
    - "em_all_infusion_meds"
    - "em_grouping_labs"
    - "em_bed_labels"
  flatfile_types:
    - ["INFUSIONMEDS", "INFUSIONMEDS"]
    - ["LABS", "LABS"]
    - ["VITALS", "VITALS"]
    - ["VENT", "VENT"]
    - ["DEMOGRAPHICS", "DEMOGRAPHICS"]
    - ["GCS", "GCS"]
    - ["ENCOUNTER", "ENCOUNTER"]
    - ["CULTURES", "CULTURES"]
    - ["BEDLOCATION", "BEDLOCATION"]
    - ["ORPROCEDURES", "ORPROCEDURES"]
    - ["DIAGNOSIS", "DIAGNOSIS"]
    - ["PROCEDURES", "PROCEDURES"]
  additional_files:
    - ["DIALYSIS", "PEACH_HD_CRRT.csv"]
    - ["IN_OUT", "in_out_AH.csv"]

# YEARLY INSTANCE FUNCTIONS AND PARAMETERS
yearly_instance:
  import_demographics:
    drop_cols: []
    index_col: ["pat_id"]
    date_cols: [] # removed 'dob'
  import_encounters:
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "ed_presentation_time"
      - "hospital_admission_date_time"
      - "hospital_discharge_date_time"
  import_infusion_meds:
    drop_cols: []
    numeric_cols:
      - "order_med_id"
      - "medication_id"
    anti_infective_group_name: "anti-infective"
    vasopressor_group_name: "vasopressor"
    index_col: ["csn"]
    date_cols:
      - "med_order_time"
      - "med_action_time"
      - "med_start"
      - "med_stop"
  import_labs:
    drop_cols: []
    group_cols:
      - "physionet"
      - "import"
      - "super_table_col_name"
      - "component_id"
    date_cols:
      - "collection_time"
      - "lab_result_time"
    index_col: ["csn"]
    numeric_cols: null
  import_vitals:
    drop_cols: []
    index_col: ["csn"]
    date_cols: ["recorded_time"]
    merge_cols: null
  import_vent:
    drop_cols: []
    index_col: ["csn"]
    numeric_cols:
      - "vent_rate_set"
      - "vent_tidal_rate_set"
      - "vent_tidal_rate_exhaled"
      - "peep"
      - "fio2"
    date_cols:
      - "recorded_time"
      - "vent_start_time"
      - "vent_stop_time"
  import_gcs:
    drop_cols: []
    index_col: ["csn"]
    numeric_col:
      - "gcs_eye_score"
      - "gcs_verbal_score"
      - "gcs_motor_score"
      - "gcs_total_score"
    date_cols: ["recorded_time"]
  import_cultures:
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "specimen_collect_time"
      - "order_time"
      - "lab_result_time"
  import_bed_locations:
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "bed_location_start"
      - "bed_location_end"
  import_procedures:
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "surgery_date"
      - "in_or_dttm"
      - "procedure_start_dttm"
      - "procedure_comp_dttm"
      - "out_or_dttm"
  import_diagnosis:
    drop_cols: []
    index_col: ["csn"]
    date_cols: ["dx_time_date"]
# COMORBIDITY SUMMARY KEYWORDS
comorbidity_summary:
  - "ICD10_quan_deyo"
  - "ICD10_quan_elix"
  # - "ICD9_ahrq"
  # - "ICD9_elix"
  # - "ICD9_quan_deyo"
  # - "ICD9_quan_elix"
  # - "ICD9_single_ccs"
  # - "ICD10_ahrq"
  # - "ICD10_elix"
  # - "ICD10_single_ccs"
# SEPSIS SUMMARY DIRECTORY PATHES
sepsis_summary: "em_sepsis_summary"
sepsis_summary_types:
  - "sofa_summary"
  - "sep3_summary"
  - "sirs_summary"
  - "sep2_summary"
  - "encounter_summary"
  - "error_summary"
  # - "ahrq_ICD10_summary"
  # - "elix_ICD10_summary"
  - "quan_deyo_ICD10_summary"
  - "quan_elix_ICD10_summary"
  # - "ccs_ICD10_summary"