# IMPORT DATA LABELS
na_values: #Entries in the data that should be converted to NA
  - "NULL"
  - "Date\\Time Correction"
  - "(null)"
  - "NOTRECORDED"
vital_col_names: #Vital names that should be converted to numeric
  - "temperature"
  - "daily_weight_kg"
  - "height_cm"
  - "sbp_line"
  - "dbp_line"
  - "map_line"
  - "sbp_cuff"
  - "dbp_cuff"
  - "map_cuff"
  - "pulse"
  - "unassisted_resp_rate"
  - "spo2"
  - "end_tidal_co2"
  - "o2_flow_rate"
vasopressor_units:
  - "norepinephrine_dose_unit"
  - "epinephrine_dose_unit"
  - "dobutamine_dose_unit"
  - "dopamine_dose_unit"
  - "phenylephrine_dose_unit"
  - "vasopressin_dose_unit"
numeric_lab_col_names:
  - "anion_gap"
  - "base_excess"
  - "bicarb_(hco3)"
  - "blood_urea_nitrogen_(bun)"
  - "calcium"
  - "calcium_adjusted"
  - "calcium_ionized"
  - "chloride"
  - "creatinine"
  - "gfr"
  - "glucose"
  - "magnesium"
  - "osmolarity"
  - "phosphorus"
  - "potassium"
  - "sodium"
  - "haptoglobin"
  - "hematocrit"
  - "hemoglobin"
  - "met_hgb"
  - "platelets"
  - "white_blood_cell_count"
  - "carboxy_hgb"
  - "alanine_aminotransferase_(alt)"
  - "albumin"
  - "alkaline_phosphatase"
  - "ammonia"
  - "aspartate_aminotransferase_(ast)"
  - "bilirubin_direct"
  - "bilirubin_total"
  - "fibrinogen"
  - "inr"
  - "lactate_dehydrogenase"
  - "lactic_acid"
  - "partial_prothrombin_time_(ptt)"
  - "prealbumin"
  - "protein"
  - "prothrombin_time_(pt)"
  - "thrombin_time"
  - "transferrin"
  - "amylase"
  - "lipase"
  - "b-type_natriuretic_peptide_(bnp)"
  - "troponin"
  - "fio2"
  - "partial_pressure_of_carbon_dioxide_(paco2)"
  - "partial_pressure_of_oxygen_(pao2)"
  - "ph"
  - "saturation_of_oxygen_(sao2)"
  - "d_dimer"
  - "hemoglobin_a1c"
  - "parathyroid_level"
  - "thyroid_stimulating_hormone_(tsh)"
  - "crp_high_sens"
  - "procalcitonin"
  - "erythrocyte_sedimentation_rate_(esr)"
  - "neutrophils"
  - "lymphocyte"
string_lab_col_names:
  - "c_diff"
  - "covid"
  - "mtp"

# Text processing configuration
text_processing:
  radiology_notes:
    text_col: "report_text"           # Column containing the report text
    clean_text: true                  # Whether to clean/normalize the text
    max_length: null                  # Maximum text length to retain (null = no limit)
    
  clinical_notes:
    text_col: "note_text"             # Column containing the note text
    clean_text: true                  # Whether to clean/normalize the text
    extract_sections: true            # Whether to extract common clinical note sections
    max_length: null                  # Maximum text length to retain (null = no limit)
    section_patterns:
      history: "(?:history\\s+of\\s+present\\s+illness|history|hpi)[\\s\\:]+(.+?)(?=\\b(?:physical examination|assessment|plan|impression|vital signs|medications)\\b|$)"
      physical_exam: "(?:physical\\s+examination|physical\\s+exam)[\\s\\:]+(.+?)(?=\\b(?:assessment|plan|impression|vital signs|medications)\\b|$)"
      assessment: "(?:assessment|impression)[\\s\\:]+(.+?)(?=\\b(?:plan|recommendations|physical examination|medications)\\b|$)"
      plan: "(?:plan|recommendations)[\\s\\:]+(.+?)(?=\\b(?:assessment|impression|physical examination|vital signs|medications)\\b|$)"