# SETUP INSTRUCTIONS
## assign unique_encounters_path to the path of the unique encounters file

# PIPELINE INSTRUCTIONS
make_temp_pickle_after_preprocessing: "no" # yes: make pickle files, no: do not make pickle files
make_supertables: "yes" # yes: make supertables, no: do not make supertables


# FILE PATHS
data_path: "/hpc/group/kamaleswaranlab/mimic_iv/mimic_flat_files"
groupings_path: "/hpc/home/yy450/link_dctrl_yy450/Sepy2.0/mimic_groupings"
temp_pickle_after_preprocessing_output_path: "/hpc/group/kamaleswaranlab/mimic_iv/sepy_output/sepy_IMPORT_pickle"
supertable_output_path: "/hpc/group/kamaleswaranlab/mimic_iv/sepy_output/mimic-supertables"
encounters_path: "ENCOUNTER_FILE"

# CSN FILTERING
encounter_type: "IN" # "EM" = Emergency, "IN" = Inpatient, "all" = all encounter types ????? 
age: "all" # "adult": age >= 18, "pediatric": age < 18, "all": all ages
specific_enc_filter: "no" # "yes": only specific encounters, "no": all encounters
# specific_enc_filter_list can be a list of csns to filter by, or a path to a csv file with a column called "csn"
specific_enc_filter_list: "/hpc/home/yy450/link_dctrl_yy450/Sepy2.0/mimic_run/sample_csn/filter_test_csn.csv"


dictionary_paths:
  # DICTIONARY PATH KEYWORDS AND STRING FOR THE GLOB FUNCTION TO MATCH IN THE groupings/comorbidities FOLDER
  comorbidity_types:
    - ["ICD9_ahrq", "*ICD9_ahrq*"]
    - ["ICD9_elix", "*ICD9_elix*"]
    - ["ICD9_quan_deyo", "*ICD9_quan_deyo*"]
    - ["ICD9_quan_elix", "*ICD9_quan_elix*"]
    - ["ICD9_single_ccs", "*ICD9_single_ccs*"]
    - ["ICD10_ahrq", "*ICD10_ahrq*"]
    - ["ICD10_elix", "*ICD10_elix*"]
    - ["ICD10_quan_deyo", "*ICD10_quan_deyo*"]
    - ["ICD10_quan_elix", "*ICD10_quan_elix*"]
    - ["ICD10_single_ccs", "*ICD10_single_ccs*"]
  # DICTIONARY PATH KEYWORDS AND STRING FOR THE GLOB FUNCTION TO MATCH IN THE groupings/ FOLDER
  grouping_types:
    # We don't need mapping/grouping files for infusion_meds, vent, etc. for MIMIC.
    - ["grouping_labs", "mimic_mapping_labs.csv"]
    - ["bed_labels", "mimic_bed_labels.csv"]
    - ["variable_chart", "mimic_variable_chart.csv"]
  flatfile_types: 
    # DICTIONARY PATH KEYWORDS AND STRING FOR THE GLOB FUNCTION TO MATCH IN THE data_path/FOLDER
    - ["ENCOUNTER", "ENCOUNTER.csv"]
    - ["DEMOGRAPHICS", "DEMOGRAPHICS.csv"]

    # - ["INFUSIONMEDS", "EMPTY_FILE.csv"]
    - ["VASOPRESSOR_MEDS", "df_vasopressor_meds.csv"]
    - ["ANTI_INFECTIVE_MEDS", "df_anti_infective_meds.csv"]
    - ["LABS", "LABS.csv"]
    - ["VITALS", "VITALS.csv"]
    - ["VENT", "VENT.csv"]
    - ["DIALYSIS", "DIALYSIS.csv"]
    - ["GCS", "GCS.csv"]
    - ["CULTURES", "CULTURES.csv"]
    - ["BEDLOCATION", "BEDLOCATION.csv"]
    - ["DIAGNOSIS", "DIAGNOSIS.csv"]
    - ["ICD_PROCEDURES", "ICD_PROCEDURES.csv"]
    - ["CPT_PROCEDURES", "CPT_PROCEDURES.csv"]
    # - ["CLINICAL_NOTES", "*CLINICAL_NOTES*"] # Uncomment if clinical notes are available
    # - ["IN_OUT", "IN_OUT.csv"]
    # - ["ORPROCEDURES", "ORPROCEDURES.csv"]

# INSTANCE FUNCTIONS AND PARAMETERS
instance:
  import_encounters:
    file_key: "ENCOUNTER"
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "ed_presentation_time"
      - "hospital_admission_date_time"
      - "hospital_discharge_date_time"
      - "deathtime"
  import_demographics:  
    file_key: "DEMOGRAPHICS"
    drop_cols: []
    index_col: ["pat_id"]
    date_cols: [] 
  import_vasopressor_meds:
    file_key: "VASOPRESSOR_MEDS"
    drop_cols:
    numeric_cols:
      - "vasopressin"
      - "dopamine"
      - "epinephrine"
      - "norepinephrine"
      - "phenylephrine"
      - "dobutamine"
      - "milrinone"
    index_col: ["csn"]
    date_cols:
      - "med_start"
      - "med_stop"
  import_anti_infective_meds:
    file_key: "ANTI_INFECTIVE_MEDS"
    drop_cols:
    index_col: ["csn"]
    date_cols:
      - "med_start"
      - "med_stop"
  import_labs:
    file_key: "LABS"
    drop_cols: []
    date_cols:
      - "collection_time"
      - "lab_result_time"
  import_vitals:
    file_key: "VITALS"
    drop_cols: []
    index_col: ["csn"]
    date_cols: ["recorded_time"]
    merge_cols: []
  import_vent:
    file_key: "VENT"
    drop_cols: []
    index_col: ["csn"]
    numeric_cols:
      - "vent_rate_set"
      - "vent_rate_total"
      - "vent_tidal_rate_set"
      - "tidal_volume_observed"
      - "tidal_volume_spontaneous"
      - "peep"
      - "fio2"
    date_cols:
      - "recorded_time"
      - "vent_start_time"
      - "vent_stop_time"
  import_dialysis:
    file_key: "DIALYSIS"
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "service_timestamp"
  import_gcs:
    file_key: "GCS"
    drop_cols: []
    index_col: ["csn"]
    numeric_col:
      - "gcs_eye_score"
      - "gcs_verbal_score"
      - "gcs_motor_score"
      - "gcs_total_score"
    date_cols: ["recorded_time"]
  import_cultures:
    file_key: "CULTURES"
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "specimen_collect_time"
      - "order_time"
      - "lab_result_time"
  import_bed_locations:
    file_key: "BEDLOCATION"
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "bed_location_start"
      - "bed_location_end"
  import_diagnosis: # Mehak says that _process_diagnosis function might not be useful?
    file_key: "DIAGNOSIS"
    drop_cols: []
    index_col: ["csn"]
    date_cols: ["dx_time_date"]
  import_cpt_procedures:
    file_key: "CPT_PROCEDURES"
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "procedure_dttm"
  import_icd_procedures:
    file_key: "ICD_PROCEDURES"
    drop_cols: []
    index_col: ["csn"]
    date_cols:
      - "procedure_date"




      
  # import_in_out:
  #   file_key: "IN_OUT"
  #   drop_cols: []
  #   numeric_cols: [] 
  #   index_col: ["csn"]
  #   date_cols:
  #     - "service_date"
  #     - "service_ts"
  #     - "order_ts"
  # import_radiology_notes:
  #   file_key: "RADIOLOGY_NOTES"
  #   drop_cols: []
  #   index_col: ["patient_id"]
  #   date_cols:
  #     - "day_verified"
  #   text_col: "doc_text"
  #   clean_text: true
  #   max_length: null
  # import_clinical_notes:
  #   file_key: "CLINICAL_NOTES"
  #   drop_cols: []
  #   index_col: ["csn"]
  #   date_cols:
  #     - "note_date"
  #     - "documented_date"
  #   text_col: "note_text"
  #   clean_text: true
  #   extract_sections: true
  #   max_length: null
  # import_procedures: # NO ORPROCEDURES FILE IN MIMIC
  #   file_key: "ORPROCEDURES"
  #   drop_cols: []
  #   index_col: ["csn"]
  #   date_cols:
  #     - "surgery_date"
  #     - "in_or_dttm"
  #     - "procedure_start_dttm"
  #     - "procedure_comp_dttm"
  #     - "out_or_dttm"


# COMORBIDITY SUMMARY KEYWORDS
comorbidity_summary:
  - "quan_deyo_ICD9"
  - "quan_elix_ICD9"
  - "quan_deyo_ICD10"
  - "quan_elix_ICD10"
  # - "ICD9_ahrq"
  # - "ICD9_elix"
  # - "ICD9_quan_deyo"
  # - "ICD9_quan_elix"
  # - "ICD9_single_ccs"
  # - "ICD10_ahrq"
  # - "ICD10_elix"
  # - "ICD10_single_ccs"


# SEPSIS SUMMARY DIRECTORY PATHS
sepsis_summary: "em_sepsis_summary"
sepsis_summary_types:
  - "sofa_summary"
  - "sep3_summary"
  - "sirs_summary"
  - "sep2_summary"
  - "encounter_summary"
  - "error_summary"
  # - "ahrq_ICD10_summary"
  # - "elix_ICD10_summary"
  # - "quan_deyo_ICD10_summary"
  # - "quan_elix_ICD10_summary" # comorbidity summary is outputted in the comorbidity_summary section
  - "comorbidity_summary"
  # - "ccs_ICD10_summary"