#!/bin/bash
#SBATCH --job-name=gonion
#SBATCH --nodes=1 --ntasks=1
#SBATCH --time=6:30:00
#SBATCH --mem=32G
#SBATCH --output=./out/gr_onion_%a.out
#SBATCH --error=./out/gr_onion_%a.err
#SBATCH --array=0-1
Y1=(2021 2022)

source /home/maror24/anaconda3/bin/deactivate
source /home/maror24/anaconda3/bin/activate rapids

python --version
python add_dialysis_history_script_grady.py ${Y1[$SLURM_ARRAY_TASK_ID]}
